version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - pip install -r requirements_dev.txt && pytest
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then python setup.py sdist bdist_wheel && twine upload --skip-existing -u __token__ -p $PYPI_TOKEN dist/*; fi
